### ISSUE TITLE
Unicode exception in nohup mode while dealing with unicode/non latin language based wikis

### ISSUE THREAD

**Issue by Jyothis** [Pathoschild/stewbot#10]
<pre>
##########################################################
###
#############################################################

Last page loaded: http://hi.wikipedia.org/w/api.php  &lt;&lt;  format=xml&noemail=&reblock=&expiry=6+hours&autoblock=&token=&lt;removed for safety&gt;&anononly=&user=27.248.120.166&reason=vandalism&allowusertalk=&action=block&nocreate=
&lt;?xml version="1.0"?&gt;&lt;api&gt;&lt;block user="27.248.120.166" userID="0" expiry="2010-04-18T09:38:27Z" reason="vandalism" anononly="" nocreate="" autoblock="" noemail="" allowusertalk="" /&gt;&lt;/api&gt;
</pre>

**Comment by Pathoschild** [comment]
This should be fixed in c11dcda48ae68a07f510a72d04001e83f0ed986b, which adds configurable logging. When running in nohup mode, add one of these to <tt>__config__.py</tt>:

<pre>
from components.logging.FileLogger import FileLogger
config.components.logger = FileLogger("path_to_file.log")
</pre>


<pre>
from components.logging.SilentLogger import SilentLogger
config.components.logger = SilentLogger()
</pre>

**Comment by Jyothis** [comment]
[2010-06-29 04:56:36] Stewardbot::onPublicMessage(data=<components.IRC.Message object at 0x867444c>)
[2010-06-29 04:56:36] components.CommandParser::handle(data=<components.IRC.Message object at 0x867444c>)
[2010-06-29 04:56:36] components.CommandParser::resolve(data=<components.IRC.Message object at 0x8500bac>)
[2010-06-29 04:56:36] components.CommandParser::_setFlags(data=<components.IRC.Message object at 0x8500bac>, flag=-8, flag_text=None)
[2010-06-29 05:00:29] Stewardbot::onPublicMessage(data=<components.IRC.Message object at 0x867444c>)
[2010-06-29 05:00:29] components.CommandParser::handle(data=<components.IRC.Message object at 0x867444c>)
[2010-06-29 05:00:29] components.CommandParser::resolve(data=<components.IRC.Message object at 0x86b326c>)
[2010-06-29 05:00:29] components.CommandParser::_setFlags(data=<components.IRC.Message object at 0x86b326c>, flag=2, flag_text=None)
[2010-06-29 05:00:29] Stewardbot::handle_translate(data=<components.IRC.Message object at 0x86b326c>)
[2010-06-29 05:00:29] Stewardbot::syntaxError(data=<components.IRC.Message object at 0x86b326c>, msg=None, count=[1, 3], condition=None)
[2010-06-29 05:00:29] components.BaseClass::isInt(text=[1, 3])
[2010-06-29 05:00:29] components.BaseClass::formatException()
[2010-06-29 05:00:29]
##########################################################

### AN EXCEPTION OCCURRED:

###

### Traceback (most recent call last):

### File "/home/jyothis/stewbot/Stewardbot.py", line 159, in onPublicMessage

### self.parser.handle( data )

### File "/home/jyothis/stewbot/components/CommandParser.py", line 176, in handle

### return self._callback( self.data, self.OKAY )

### File "/home/jyothis/stewbot/components/CommandParser.py", line 375, in _callback

### method( data )

### File "/home/jyothis/stewbot/Stewardbot.py", line 818, in handle_translate

### result = self.browser.translate( source=source, target=target, text=text )

### File "/home/jyothis/stewbot/components/Browser.py", line 1142, in translate

### self.trace()

### File "/home/jyothis/stewbot/components/BaseClass.py", line 106, in trace

### self.logger.Log('%s::%s%s' % (module, function, arg_string))

### File "/home/jyothis/stewbot/components/logging/FileLogger.py", line 20, in Log

### self.file.write("[%s] %s\n" % (time.strftime("%Y-%m-%d %H:%M:%S"), str(message)))

### UnicodeEncodeError: 'ascii' codec can't encode characters in position 35-38: ordinal not in range(128)

#############################################################
[2010-06-29 05:00:29] components.IRC::sendMessage(chan=#Jyothis, nick=None, msg=unhandled exception: UnicodeEncodeError: 'ascii' codec can't encode characters in position 35-38: ordinal not in range(128).   File "/home/jyothis/stewbot/components/logging/FileLogger.py", line 20, in Log (see terminal))
[2010-06-29 05:00:29] components.IRC::_sendMessage(target=#Jyothis, message=unhandled exception: UnicodeEncodeError: 'ascii' codec can't encode characters in

**Comment by Jyothis** [comment]
issued command - !translate 尾崎隆吉
server info - run a uname -a on willow.
bot is running under nohup

**Comment by Jyothis** [comment]
bot started as  nohup python **init**.py &

**Comment by Pathoschild** [comment]
Should be fixed in 7bbb46607e232346a6ac1b117628c937c8ac3c96.

**Comment by Pathoschild** [comment]
Confirmed fixed.
